name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour, UTC time
  workflow_dispatch:  # Allow manual run too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping request
        run: curl -sSf https://transnlp.streamlit.app/
